src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Category;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Price;

    /**
     * @ORM\ManyToMany(targetEntity=Order::class, mappedBy="name", cascade={"remove"})
     */
    private $orders;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(?float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->addName($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeName($this);
        }

        return $this;
    }

    public function getImage()
    {
        return $this->Image;
    }

    public function setImage($Image)
    {
        if ($Image != null){
            $this->Image = $Image;
        }
        
        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('Description')
            ->add('Price', MoneyType::class,
            [
            'currency' => "USD"
            ])
            ->add('Category', EntityType::class,
            [
                'class' => Category::class,
                'choice_label' => "name"
            ])
            -> add('Image', FileType::class,
            [
                // 'label' => 'Product Image',
                'data_class' => null,
                'required'=> is_null($builder->getData()->getImage())
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\AddToCartType;
use App\Form\ProductType;
use Doctrine\DBAL\Abstraction\Result;
use Doctrine\ORM\Query\AST\Functions\FunctionNode;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

use function PHPUnit\Framework\throwException;

class ProductController extends AbstractController
{
    /**
   * @Route("/product", name="product_list")
   */
  public function listProduct (){
    $products = $this->getDoctrine()
                       ->getRepository(Product::class)
                       ->findAll();
    return $this->render(
      "product/index.html.twig",
      [
        'products' => $products
      ]
      );
  }

  /**
   * @Route("/product/detail/{id}", name="product_detail")
   */
  public function detailProduct ($id) {
    $product = $this->getDoctrine()
                       ->getRepository(Product::class)
                       ->find($id);
    if ($product == null){
      $this->addFlash("Warning", "Product ID is invalid!");
      return $this->redirectToRoute("product_list");    
    }
    return $this->render(
      "product/detail.html.twig",
      [
        'product' => $product
      ]
      );
  }

  /**
   * @Route("/product/delete/{id}", name="product_delete")
   */
  public function deleteProduct ($id) {
    $product = $this->getDoctrine()
                     ->getRepository(Product::class)
                     ->find($id);
    if ($product == null){
      $this->addFlash("Warning", "Product ID is invalid!");
      return $this->redirectToRoute("product_list");
    }
    $manager = $this->getDoctrine()
                    ->getManager();
    $manager->remove($product);
    $manager->flush();
    $this->addFlash("Success", "Product has been deleted!");
    return $this->redirectToRoute("product_list");
  }

  /**
   * @Route("/product/create", name="product_create")
   */
  public function createProduct (Request $request) {
    $product = new Product();
    $form = $this->createForm(ProductType::class, $product);
    $form->handleRequest($request);

    if($form->isSubmitted() && $form->isValid()){

      $image = $product->getImage();

      // create unique image name
      $fileName = md5(uniqid());
      $fileExtension = $image->getExtension();
      $imageName = $fileName . '.' . $fileExtension;

      // move uploaded image to defined location
      try {
        $image->move(
          $this->getParameter('product_image'), $imageName
        );
      } catch (FileException $e) {
        throwException($e);
      }
      
      $product->setImage($imageName);

      $manager = $this->getDoctrine() 
                      ->getManager();
      $manager->persist($product);
      $manager->flush();
      $this->addFlash("Success", "Add product successfully!!");
      return $this->redirectToRoute("product_list");
    }

    return $this->render(
      "product/create.html.twig",
      [
        "form" => $form->createView()
      ]
    );
  }

  /**
   * @Route("/product/update/{id}", name="product_update")
   */
  public function updateProduct (Request $request, $id) {
    $product = $this->getDoctrine()
                     ->getRepository(Product::class)
                     ->find($id);
    
    $form = $this->createForm(ProductType::class, $product);
    $form->handleRequest($request);

    if($form->isSubmitted() && $form->isValid()){
      $uploadedFile = $form['Image']->getData();
      if ($uploadedFile != null){
        $image = $product->getImage();

        // create unique image name
        $fileName = md5(uniqid());
        $fileExtension = $image->getExtension();
        $imageName = $fileName . '.' . $fileExtension;

        // move uploaded image to defined location
        try {
          $image->move(
            $this->getParameter('product_image'), $imageName
          );
        } catch (FileException $e) {
          throwException($e);
        }
        
        $product->setImage($imageName);
      }
      $manager = $this->getDoctrine() 
                      ->getManager();
      $manager->persist($product);
      $manager->flush();
      $this->addFlash("Success", "Update product successfully!!");
      return $this->redirectToRoute("product_list");
    }

    return $this->render(
      "product/update.html.twig",
      [
        "form" => $form->createView()
      ]
    );
  }
}

templates/product/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Product{% endblock %}

{% block body %}
<div class="container-fluid mt-3">
    <h2 class="text-center mt-2">CREATE PRODUCT</h2>
    <div class="col-md-6"></div>
        {{ form_start (form) }}
            <div class="form-group">
                <p class="text-info text-bold"> Product name </p>
                {{form_widget (form.Name, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <p class="text-info text-bold"> Product Description </p>
                {{form_widget (form.Description, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <p class="text-info text-bold"> Product Price </p>
                {{form_widget (form.Price, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <p class="text-info text-bold"> Category </p>
                {{form_widget (form.Category, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <p class="text-info text-bold"> Product Image </p>
                {{form_widget (form.Image, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <button class="btn btn-primary mt-3 btn-">CREATE</button>
            </div>
        {{ form_end (form)}}
    
</div>
{% endblock %}

templates/product/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product Detail{% endblock %}

{% block body %}
<div class="container mt-3">
<a class="btn btn-primary" href="{{ path ("product_list") }}">List Product </a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Product Name</th>
                <th scope="col">Product Description</th>
                <th scope="col">Product Price</th>
                <th scope="col">Product Category</th>
                <th scope="col">Product Image</th>
                <th scope="col">Add</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="row">{{ product.name }}</td>
                <td scope="row">{{ product.description }}</td>
                <td scope="row">{{ product.price }}</td>
                <td scope="row">
                        <a href="{{ path('category_detail', {'id': product.category.id}) }}">
                        {{ product.category.name }}
                        <br>
                </td>
                <td scope="row">
                    <img src="{{ asset ('images/products/' ~ product.image) }}"width="100px" height="120px">
                </td>
                
                <td scope="row">
                    <a class="btn btn-warning" href="{{ path('product_update', {'id': product.id }) }}">Update</a>
                    <a class="btn btn-danger" href="{{ path('product_delete', {'id': product.id }) }}">Delete</a>
                </td> 
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product Information{% endblock %}

{% block body %}

<div class="container">
    {% for flash in app.flashes("Success") %}
        <p class="alert alert-primary"> {{ flash }} </p>
    {% endfor %}
    {% for flash in app.flashes("Warning") %}
        <p class="alert alert-danger"> {{ flash }} </p>
    {% endfor %}
</div>

<div class="container mt-3">
    <a class="btn btn-primary" href="{{ path('product_create') }}">Create Product</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Product ID</th>
                <th scope="col">Product Name</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td scope="row">{{ product.id }}</td>
                <td scope="row">{{ product.name }}</td>
                <td scope="row">
                    <a class="btn btn-info" href="{{ path('product_detail', {'id': product.id }) }}">Detail</a>
                    <a class="btn btn-warning" href="{{ path('product_update', {'id': product.id }) }}">Update</a>
                    <a class="btn btn-danger" href="{{ path('product_delete', {'id': product.id }) }}">Delete</a>
                </td>            
            </tr>
        {% endfor %}   
        </tbody>
    </table>
</div>
{% endblock %}

templates/product/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update product{% endblock %}

{% block body %}
<div class="container-fluid mt-3">
    <h2 class="text-center mt-2">UPDATE PRODUCT</h2>
    <div class="col-md-6"></div>
        {{ form_start (form) }}
            <div class="form-group">
                <p class="text-info text-bold"> Product name </p>
                {{form_widget (form.Name, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <p class="text-info text-bold"> Product Description </p>
                {{form_widget (form.Description, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <p class="text-info text-bold"> Product Price </p>
                {{form_widget (form.Price, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <p class="text-info text-bold"> Category </p>
                {{form_widget (form.Category, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <p class="text-info text-bold"> Product Image </p>
                {{form_widget (form.Image, {'attr': {'class': 'form-control'}})}}
            </div>
            <div class="form-group">
                <button class="btn btn-primary mt-3 btn-">CREATE</button>
            </div>
        {{ form_end (form)}}
    
</div>
{% endblock %}