src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity=Product::class, inversedBy="orders")
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Quantity;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $CustomerName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CustomerAddress;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $Phone;

    public function __construct()
    {
        $this->name = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Product[]
     */
    public function getName(): Collection
    {
        return $this->name;
    }

    public function addName(Product $name): self
    {
        if (!$this->name->contains($name)) {
            $this->name[] = $name;
        }

        return $this;
    }

    public function removeName(Product $name): self
    {
        $this->name->removeElement($name);

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(?int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getCustomerName(): ?string
    {
        return $this->CustomerName;
    }

    public function setCustomerName(?string $CustomerName): self
    {
        $this->CustomerName = $CustomerName;

        return $this;
    }

    public function getCustomerAddress(): ?string
    {
        return $this->CustomerAddress;
    }

    public function setCustomerAddress(?string $CustomerAddress): self
    {
        $this->CustomerAddress = $CustomerAddress;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(?string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Entity\Product;
use Doctrine\ORM\EntityRepository;
use PHPUnit\TextUI\XmlConfiguration\CodeCoverage\Report\Text;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', EntityType::class, [
            'class' => Product::class,
            'choice_label' => 'name',
            'multiple' => true,
            'expanded' => false
            ])
            ->add('Quantity', IntegerType::class)
            ->add('CustomerName', TextType::class)
            ->add('CustomerAddress', TextType::class)
            ->add('Phone')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\OrderType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderController extends AbstractController
{
    /**
     * @Route("/order", name="order_list")
     */
    public function listOrder () {
        $orders = $this->getDoctrine()
                        ->getRepository(Order::class)
                        ->findAll();
    
        return $this->render(
                        "order/index.html.twig",
                        [
                            'orders' => $orders
                        ]
                     );
    }

    /**
     * @Route("/order/detail/{id}", name="order_detail")
     */
    public function detailOrder ($id) {
        $order = $this->getDoctrine()
                       ->getRepository(Order::class)
                       ->find($id);

        if ($order == null) {
            $this->addFlash("Error", "Order ID in invalid");
            return $this->redirectToRoute("order_list");
        }

        return $this->render(
                        "order/detail.html.twig",
                        [
                          'order' => $order
                        ]
        );
    }

    
    /**
     * @Route("/order/delete/{id}", name="order_delete")
     */
    public function deleteOrder ($id)
    {
        $order = $this->getDoctrine()
                          ->getRepository(Order::class)
                          ->find($id);
        if($order == null) {
            $this->addFlash("Error", "Invalid Order ID");
            return $this->redirectToRoute("order_list");
        }
        $manager = $this->getDoctrine()
                        ->getManager();
        $manager->remove($order);
        $manager->flush();
        $this->addFlash("Info", "Order has been deleted");    
        return $this->redirectToRoute("order_list");
    }

    /**
     * @Route("/order/create", name="order_create")
     */
    public function createOrder (Request $request)
    {
        $order = new Order();
        $form = $this->createForm(OrderType::class,$order);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager = $this->getDoctrine()
                            ->getManager();
            $manager->persist($order);
            $manager->flush();

            $this->addFlash("Info", "Order has been added!");
            return $this->redirectToRoute("order_list");
        }
        return $this->render(
            "order/create.html.twig",
            [
                "form" => $form->createView()
            ]
        );
    }
}

templates/order/create.html.twig
{% extends "base.html.twig" %}
{% block title %} Add an Order {% endblock %}

{% block body %}
    <div class="container-fluid mt-3"> 
        <h2 class="text-center mt-3"> Create Order </h2>
        <div class="col-md-8">         </div>
            {{ form_start (form) }}
                <div class="form-group">
                    {{ form_label (form.name) }}
                    {{ form_widget (form.name, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Quantity) }}
                    {{ form_widget (form.Quantity, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.CustomerName) }}
                    {{ form_widget (form.CustomerName, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.CustomerAddress) }}
                    {{ form_widget (form.CustomerAddress, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Phone) }}
                    {{ form_widget (form.Phone, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group text-center mt-3">
                    <button class="btn btn-danger">Create</button>
                </div>
            {{ form_end (form) }}
    </div>
{% endblock %}

templates/order/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order Detail{% endblock %}

{% block body %}

<div class="container mt-3">
    <table class = "table">
        <thead>
            <tr>
                <th scope="col">Order ID</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Customer Name</th>
                <th scope="col">Customer Location</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="row">{{ order.id }}</td>
                <td scope="row">
                {% for a in order.name %}
                  <a href="{{ path('product_detail', {'id' : a.id }) }}">
                       {{ a.name }}
                  </a>
                  <br>
                {% endfor %}
                </td>
                <td scope="row">{{ order.quantity }}</td>
                <td scope="row">{{ order.customername }}</td>
                <td scope="row">{{ order.customeraddress }}</td>
                <td scope="row">{{ order.phone }}</td>             
                <td scope="row">
                <a class="btn btn-danger" href="{{ path ('order_delete', {'id': order.id}) }}"onclick="return confirm('This Infomation will be deleted!')">Delete</a>
            </tr>
        </tbody>
</div>
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}

<div class="container mt-3">
    {% for flash in app.flashes("Success") %}
        <p class="alert alert-primary"> {{ flash }} </p>
    {% endfor %}
    {% for flash in app.flashes("Warning") %}
        <p class="alert alert-danger"> {{ flash }} </p>
    {% endfor %}
</div>
<div class="container-fluid">
<a class="btn" href="{{ path ( 'order_create' ) }}">Add New Order</a>
<table class = "table">
    <thead>
        <tr>
            <th scope="col">Order ID</th>
            <th scope="col">Customer Name</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for order in orders %}
        <tr>
            <td scope="row">{{ order.id}}</td>
            <td scope="row">{{ order.customername}}</td>
            <td scope="row">
                <a class="btn btn-primary" href="{{ path('order_detail', {'id': order.id} )}}">Detail</a>
                <a class="btn btn-danger" href="{{ path('order_delete', {'id': order.id} )}}"
                onclick="return confirm('This publisher will be deleted!')">Delete</a>
        </tr>
    </tbody>
    {% endfor %}
</div>
{% endblock %}